# Generated by Django 5.2.7 on 2025-11-20 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_guest', models.CharField(blank=True, help_text='Nom si non inscrit', max_length=100)),
                ('email_guest', models.EmailField(blank=True, help_text='Email si non inscrit', max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
    ]
