# Generated by Django 5.2.7 on 2025-11-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='messagerie.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email_guest',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='nom_guest',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
