# Generated by Django 5.2.7 on 2025-11-05 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la catégorie', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL (généré automatiquement)', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre de l'article", max_length=250)),
                ('slug', models.SlugField(blank=True, help_text='URL (généré automatiquement)', max_length=270, unique=True)),
                ('contenu', models.TextField(help_text="Contenu de l'article (Markdown ou texte brut)")),
                ('image_banniere', models.ImageField(blank=True, help_text="Facultatif. Image d'en-tête.", null=True, upload_to='article_banners/')),
                ('statut', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié')], default='DRAFT', help_text="Statut de l'article (Brouillon ou Publié)", max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(help_text="L'auteur de l'article", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_ecrits', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, help_text="Catégories de l'article", related_name='articles', to='blog.categorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(help_text='Le contenu du commentaire', max_length=2000)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('approuve', models.BooleanField(default=True, help_text="Statut d'approbation du commentaire")),
                ('article', models.ForeignKey(help_text="L'article auquel ce commentaire est lié", on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='blog.article')),
                ('auteur', models.ForeignKey(help_text="L'auteur du commentaire", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires_ecrits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['date_creation'],
            },
        ),
    ]
