# Generated by Django 5.2.7 on 2025-11-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='est_a_la_une',
            field=models.IntegerField(blank=True, help_text="Entrez 1, 2 ou 3 pour définir l'ordre sur l'accueil. Laissez vide pour ne pas afficher.", null=True, verbose_name='Position à la une'),
        ),
    ]
