# Generated by Django 5.2.7 on 2025-11-05 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text="Définit si l'utilisateur peut se connecter au site d'administration.")),
                ('is_active', models.BooleanField(default=True, help_text='Désactivez ceci au lieu de supprimer des comptes.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('pseudo', models.CharField(blank=True, help_text='Facultatif. Le pseudo affiché sur le site.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Facultatif. Une courte description de vous-même.', max_length=500)),
                ('profile_picture', models.ImageField(blank=True, help_text='Facultatif. Votre photo de profil.', null=True, upload_to='profile_pics/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
